version: '3.8'

services:
  app:
    build: .
    command: sh -c "PYTHONPATH=/app python app/main.py"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
